# Numpy

In [1]:
import numpy as np

### Checking version of library

print(np.__version__)

## 0D Matrix OR Scalar

In [10]:
x1=np.array(55)
print(55)
print(type(x1))
print(x1.ndim)

55
<class 'numpy.ndarray'>
0


## 1D Matrix OR Vector

In [7]:
x2=np.array([1,2,3,4,5,6])
print(x2)
print(type(x2))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


## 2D Matrix

In [38]:
x3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(x3)
print(type(x3))
print(x3.ndim)
print(x3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>
3
(2, 2, 2)


## 3D Matrix

In [42]:
x4=np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]])
print(x4)
print(x4.ndim)
print(x4.shape)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
4
(2, 2, 2, 2)


## Coverting 1D to 5D Matrix

In [112]:
x5=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x5)
print(type(x5))
print("*"*50)
x6=x5.reshape(3,1,2,2,1)
print(x6)
print(type(x6))
print(x6.ndim)
print(x6.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>
**************************************************
[[[[[ 1]
    [ 2]]

   [[ 3]
    [ 4]]]]



 [[[[ 5]
    [ 6]]

   [[ 7]
    [ 8]]]]



 [[[[ 9]
    [10]]

   [[11]
    [12]]]]]
<class 'numpy.ndarray'>
5
(3, 1, 2, 2, 1)


## Solving Linear Algebra

In [134]:
x1=np.array([[4,3,5],[-5,9,3],[15,-4,5]])
y1=np.array([20,21,12])
sol=np.linalg.solve(x1,y1)
print(sol)


[0.19708029 1.45255474 2.97080292]


In [136]:
x=np.array([[1,2,3],[23,-4,-2],[6,-3,8]])
y=np.array([76,72,19])
sol=np.linalg.solve(x,y)
print(sol)

[ 8.02831858 25.25132743  5.82300885]


## Coverting Image Format into Matrix

In [142]:
from matplotlib.image import imread
hi=imread("C://Users//abc//Downloads//ganapati1.jpg")
hi

array([[[23, 27, 28],
        [ 6, 10, 19],
        [ 6, 12, 26],
        ...,
        [19, 19, 21],
        [23, 19, 18],
        [33, 25, 22]],

       [[22, 26, 27],
        [ 5,  9, 18],
        [ 4, 10, 24],
        ...,
        [18, 18, 20],
        [23, 19, 18],
        [33, 25, 22]],

       [[21, 25, 26],
        [ 4,  8, 17],
        [ 3,  9, 23],
        ...,
        [18, 18, 20],
        [23, 19, 18],
        [33, 25, 22]],

       ...,

       [[24, 26, 23],
        [ 0,  0,  5],
        [ 5,  5, 17],
        ...,
        [29, 23, 23],
        [34, 24, 22],
        [42, 31, 27]],

       [[25, 27, 24],
        [ 0,  1,  6],
        [ 4,  6, 18],
        ...,
        [30, 24, 24],
        [33, 25, 22],
        [42, 31, 27]],

       [[27, 29, 26],
        [ 2,  3,  8],
        [ 7,  9, 21],
        ...,
        [30, 24, 24],
        [33, 25, 22],
        [42, 31, 27]]], dtype=uint8)

# Matrix Solving

In [151]:
test=np.array([[1,2j,32],[4,5j,3],[3,4j,6]])
print(test)
print("__"*50)
print(np.linalg.matrix_rank(test))
print("__"*50)
print(np.trace(test))
print("__"*50)
print(np.linalg.det(test))
print("__"*50)
print(np.linalg.inv(test))

[[ 1.+0.j  0.+2.j 32.+0.j]
 [ 4.+0.j  0.+5.j  3.+0.j]
 [ 3.+0.j  0.+4.j  6.+0.j]]
____________________________________________________________________________________________________
3
____________________________________________________________________________________________________
(7+5j)
____________________________________________________________________________________________________
19.999999999999996j
____________________________________________________________________________________________________
[[ 0.9 +0.j    5.8 +0.j   -7.7 +0.j  ]
 [ 0.  +0.75j  0.  +4.5j   0.  -6.25j]
 [ 0.05+0.j    0.1 +0.j   -0.15-0.j  ]]


### Power of Matrix

In [153]:
np.linalg.matrix_power(test,3)

array([[ 729. +546.j, -690.+1040.j, 4418. +682.j],
       [ 351. +145.j, -200. +485.j, 1217. +790.j],
       [ 337. +172.j, -230. +470.j, 1404. +674.j]])

# Eigen vector

In [156]:
test1=np.array([[1,2],[3,4]])
print(test1)
print()
c,d=np.linalg.eigh(test1)
print(c)
print()
print(d)

[[1 2]
 [3 4]]
[-0.85410197  5.85410197]
[[-0.85065081  0.52573111]
 [ 0.52573111  0.85065081]]


## Transpose(Row to Coloumn ,Coloumn to Row)

In [158]:
np.transpose(test1)

array([[1, 3],
       [2, 4]])

## Mean,Mode And Median

In [166]:
from scipy import stats 
speed=np.array([1,2,3,4,5,5,6,7])
feq=np.array([34,23,32,43,43,232])
m=np.mean(speed)
m=np.mean(feq)
print(m)
m1=stats.mode(speed)
m1=stats.mode(feq)
print(m1)
m2=np.median(speed)
m2=np.median(feq)
print(m2)

67.83333333333333
ModeResult(mode=43, count=2)
38.5


## Standard Deviation

In [170]:
speed=np.array([53,62,73,23,23,21,87,78,])
print(speed.std())
print(speed.var())

25.20912533191106
635.5


## Percentile

In [182]:
speed1=np.array([53,62,73,23,23,21,87,78,34])
np.percentile(speed,100)

87.0